OCT-715: Replace BigNumber with BigInt
golemfoundation/octant pull request #10
Opened 2024-02-21 10:48 UTC by jmikolajczyk

2024-02-21 14:44 UTC, aziolek requested changes
Please add signatures to the commits.

2024-02-22 08:24 UTC, jmikolajczyk commented
> Please add signatures to the commits.

@aziolek done

2024-02-22 10:36 UTC, aziolek commented
> > Please add signatures to the commits.
> 
> @aziolek done

All commits need to be signed, so you need for `push --force` and override he history.

2024-02-23 10:01 UTC, aziolek commented on client/src/views/AllocationView/AllocationView.tsx
> -      !rewardsForProposalsNew
That looks suspicious. I will dig deeper why it was here, maybe truly without reason.

2024-02-23 11:15 UTC, jmikolajczyk commented on client/src/components/Allocation/AllocationItemRewards/AllocationItemRewards.tsx
> +          ),
Implementation mistake -> `bigintAbs` should get subtract operation as a param.

2024-02-23 11:20 UTC, jmikolajczyk commented on client/src/hooks/mutations/useLock.ts
> +        args: [`0x${value.toString(16)}`],
nope :(

2024-02-23 12:38 UTC, aziolek requested changes
When AW is open but user does not have `individualReward`, in `AllocationView`:
1. Inputs are not disabled.
2. Weird `0 ETH /` is shown in place of rewards.

Image below:

![image](https://github.com/golemfoundation/octant/assets/25887234/d6fbc591-5536-4c36-959f-4e45d16522c3)

Both problems do not happen on the current `master`:

![image](https://github.com/golemfoundation/octant/assets/25887234/47e91479-9e9a-4588-9401-5af59d98999f)

2024-02-26 08:03 UTC, aziolek commented on client/src/components/Earn/EarnTipTiles/EarnTipTiles.tsx
> +      !individualReward &&
`isAllocateRewardsTipVisible` when the user doesn't have `individualReward`? Why?

2024-02-26 08:05 UTC, aziolek commented on client/src/components/Earn/EarnTipTiles/EarnTipTiles.tsx
> +      !individualReward &&
`master` code for that: `!individualReward?.isZero()`.

2024-02-26 13:19 UTC, aziolek approved these changes

2024-02-26 14:31 UTC, merged