fix: use user_address as passed as a parameter in /allocate API
golemfoundation/octant pull request #112
Opened 2024-03-29 10:46 UTC by paulperegud

Previously we relied on erecover. This doesn't work for EIP-1271.

2024-03-29 10:51 UTC, leoni-q approved these changes

2024-03-29 10:56 UTC, aziolek requested changes

2024-03-29 10:56 UTC, aziolek commented on backend/app/infrastructure/routes/allocations.py
> +        "user_address": fields.String(
@paulperegud: please change to camelCase, unifying all the fields across the endpoint and most of the stack.
```suggestion
        "userAddress": fields.String(
```

2024-03-29 10:58 UTC, aziolek commented on backend/app/infrastructure/routes/allocations.py
> +        "user_address": fields.String(
[The client is now adjusted and sends camelCased `userAddress`](https://github.com/golemfoundation/octant/pull/112/commits/cb639db6379f6b01d36126f3a688844528bff464).

2024-03-30 10:36 UTC, kgarbacinski requested changes
please align ```handle_allocate``` from ```app.infrastracture.events``` with new changes that call controller.allocate in the old way

2024-04-02 10:14 UTC, leoni-q approved these changes

2024-04-02 10:14 UTC, leoni-q commented on backend/tests/conftest.py
> +                "user_address": user_address,
```suggestion
                "userAddress": user_address,
```

2024-04-02 10:16 UTC, leoni-q approved these changes

2024-04-02 11:44 UTC, kgarbacinski approved these changes

2024-04-02 11:58 UTC, merged