OCT-1674: E2E: App wide fiat support - metrics view
golemfoundation/octant pull request #246
Opened 2024-06-10 09:39 UTC by jmikolajczyk

## Description

## Definition of Done

1. [ ] Acceptance criteria are met.
2. [ ] PR is manually tested before the merge by developer(s).
    - [ ] Happy path is manually checked.
3. [ ] PR is manually tested by QA when their assistance is required (1).
    - [ ] Octant Areas & Test Cases are checked for impact and updated if required (2).
4. [ ] Unit tests are added unless there is a reason to omit them.
5. [ ] Automated tests are added when required.
6. [ ] The code is merged.
7. [ ] Tech documentation is added / updated, reviewed and approved (including mandatory approval by a code owner, should such exist for changed files).
    - [ ] BE: Swagger documentation is updated.
8. [ ] When required by QA:
    - [ ] Deployed to the relevant environment.
    - [ ] Passed system tests.

---

(1) Developer(s) in coordination with QA decide whether it's required. For small tickets introducing small changes QA assistance is most probably not required.

(2) [Octant Areas & Test Cases](https://docs.google.com/spreadsheets/d/1cRe6dxuKJV3a4ZskAwWEPvrFkQm6rEfyUCYwLTYw_Cc).

2024-06-11 12:58 UTC, aziolek requested changes
Please add a test that should have failed and catch 3) from comment [here](https://github.com/golemfoundation/octant/pull/216#pullrequestreview-2110335910).

2024-06-11 13:09 UTC, aziolek requested changes

2024-06-11 13:09 UTC, aziolek commented on client/cypress/e2e/metrics.cy.ts
> +  cy.get('[data-test=Navbar__Button--Settings]').click();
Please use `navigateWithCheck` util. This function is shared in all tests. Please move it to utils.

2024-06-11 13:09 UTC, aziolek commented on client/cypress/e2e/metrics.cy.ts
> +  cy.get('[data-test=Navbar__Button--Metrics]').click();
Please use `navigateWithCheck` util. This function is shared in all tests. Please move it to utils.

2024-06-13 12:07 UTC, aziolek requested changes

2024-06-13 12:07 UTC, aziolek commented on client/cypress/e2e/metrics.cy.ts
> +      // cy.setupMetamask();
Comment not required?

2024-06-13 12:10 UTC, aziolek requested changes
Where is the test added?
=> https://github.com/golemfoundation/octant/pull/246#pullrequestreview-2110390416

2024-06-14 05:26 UTC, jmikolajczyk commented
> Where is the test added? => [#246 (review)](https://github.com/golemfoundation/octant/pull/246#pullrequestreview-2110390416)

In metrics.cy.ts file : )

2024-06-14 11:46 UTC, aziolek approved these changes

2024-06-14 12:56 UTC, merged