OCT-1803: Adds migration to change uq score for users
golemfoundation/octant pull request #349
Opened 2024-07-19 12:34 UTC by adam-gf

## Description
Adds migration to change uq score for users

## Definition of Done

1. [ ] Acceptance criteria are met.
2. [ ] PR is manually tested before the merge by developer(s).
    - [ ] Happy path is manually checked.
3. [ ] PR is manually tested by QA when their assistance is required (1).
    - [ ] Octant Areas & Test Cases are checked for impact and updated if required (2).
4. [ ] Unit tests are added unless there is a reason to omit them.
5. [ ] Automated tests are added when required.
6. [ ] The code is merged.
7. [ ] Tech documentation is added / updated, reviewed and approved (including mandatory approval by a code owner, should such exist for changed files).
    - [ ] BE: Swagger documentation is updated.
8. [ ] When required by QA:
    - [ ] Deployed to the relevant environment.
    - [ ] Passed system tests.

---

(1) Developer(s) in coordination with QA decide whether it's required. For small tickets introducing small changes QA assistance is most probably not required.

(2) [Octant Areas & Test Cases](https://docs.google.com/spreadsheets/d/1cRe6dxuKJV3a4ZskAwWEPvrFkQm6rEfyUCYwLTYw_Cc).

2024-07-19 12:40 UTC, kgarbacinski commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_waitlist.py
> +upgrade()
why is it here?

2024-07-19 12:40 UTC, kgarbacinski commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_waitlist.py
> +# revision identifiers, used by Alembic.
to remove

2024-07-19 12:40 UTC, kgarbacinski commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_waitlist.py
> +    # Revert the changes made in the upgrade
comment to remove

2024-07-19 12:41 UTC, kgarbacinski commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_waitlist.py
> +        WHERE epoch = 5 AND user_id IN (
I think we need it for E4, not E5

2024-07-19 12:49 UTC, kgarbacinski commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_waitlist.py
> +        WHERE epoch = 5 AND user_id IN (
you can also consider adding another predicate: ```WHERE score = 0.2```

2024-07-19 13:23 UTC, paulperegud submitted a review, later dismissed

2024-07-19 13:23 UTC, paulperegud commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_waitlist.py
> +            SELECT id FROM users WHERE address IN (
Strictly speaking this downgrade doesn't reverse the upgrade. Not sure if we should care about it ATM.

2024-07-19 13:27 UTC, paulperegud commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_waitlist.py
> +"""update uq score for waitlist
Why "waitlist"? Isn't it a guest list?

2024-07-19 13:56 UTC, aziolek commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_waitlist.py
> +"""update uq score for waitlist
Either `whitelist` or `guestlist`.

2024-07-19 13:56 UTC, aziolek requested changes
This waits for https://github.com/golemfoundation/octant/pull/350.

2024-07-19 14:12 UTC, paulperegud commented
@adam-gf please also recheck if addresses should be normalized before comparison with addresses in our DB. AFAIR we store all addresses in normalized with `to_checksum_address(...)`.

2024-07-22 09:24 UTC, kgarbacinski commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_guestlist.py
> +        UPDATE uniqueness_quotients
the possible issue here is that we'll downgrade every person from the guestlist (not only ppl from the upgrade) but it's not very likely to execute this so not a blocker

2024-07-22 09:24 UTC, kgarbacinski approved these changes

2024-07-22 09:24 UTC, paulperegud approved these changes

2024-07-22 10:17 UTC, adam-gf commented on backend/migrations/versions/5d3bf271b78d_update_uq_score_for_guestlist.py
> +raw_addresses = [
Only for those who have UQ score  set in db, so only those who voted.

2024-07-22 10:33 UTC, aziolek commented
https://github.com/golemfoundation/octant/pull/350 is merged.

2024-07-22 10:48 UTC, 0xartem approved these changes

2024-07-22 10:50 UTC, aziolek approved these changes

2024-07-22 10:50 UTC, merged