OCT-2127 Project E2E
golemfoundation/octant pull request #586
Opened 2024-12-11 12:20 UTC by aziolek

## Description

## Definition of Done

1. [ ] If required, the desciption of your change is added to the [QA changelog](https://www.notion.so/octantapp/Changelog-for-the-QA-d96fa3b411cf488bb1d8d9a598d88281) 
2. [ ] Acceptance criteria are met.
3. [ ] PR is manually tested before the merge by developer(s).
    - [ ] Happy path is manually checked.
4. [ ] PR is manually tested by QA when their assistance is required (1).
    - [ ] Octant Areas & Test Cases are checked for impact and updated if required (2).
5. [ ] Unit tests are added unless there is a reason to omit them.
6. [ ] Automated tests are added when required.
7. [ ] The code is merged.
8. [ ] Tech documentation is added / updated, reviewed and approved (including mandatory approval by a code owner, should such exist for changed files).
    - [ ] BE: Swagger documentation is updated.
9. [ ] When required by QA:
    - [ ] Deployed to the relevant environment.
    - [ ] Passed system tests.

---

(1) Developer(s) in coordination with QA decide whether it's required. For small tickets introducing small changes QA assistance is most probably not required.

(2) [Octant Areas & Test Cases](https://docs.google.com/spreadsheets/d/1cRe6dxuKJV3a4ZskAwWEPvrFkQm6rEfyUCYwLTYw_Cc).

2024-12-17 13:08 UTC, jmikolajczyk commented
@aziolek ACs from [task](https://linear.app/golemfoundation/issue/OCT-2127/project-e2e) are not met. If you want to modify something please keep ACs up to date.

2024-12-17 13:08 UTC, jmikolajczyk requested changes

2024-12-18 12:13 UTC, aziolek commented on client/cypress/e2e/_16project.cy.ts
> +        cy.get('[data-test=Navbar__numberOfAllocations]').should('not.exist');
Done.

2024-12-18 12:13 UTC, aziolek commented on client/cypress/e2e/_16project.cy.ts
> +      // it(`shows current total (${IS_CRYPTO_MAIN_VALUE_DISPLAY}: false)`, () => {
Done.

2024-12-18 13:29 UTC, jmikolajczyk commented on client/cypress/utils/e2e.ts
> +    cy.getAllLocalStorage().then(() => {
The same is checked in `return`.

2024-12-18 13:33 UTC, aziolek commented on client/cypress/utils/e2e.ts
> +    cy.getAllLocalStorage().then(() => {
Done.

2024-12-18 18:08 UTC, jmikolajczyk requested changes

2024-12-19 10:03 UTC, jmikolajczyk approved these changes

2024-12-19 11:20 UTC, merged