OCT-2263: Community onboarding through Sablier
golemfoundation/octant pull request #600
Opened 2024-12-20 11:17 UTC by kgarbacinski

## Description

## Definition of Done

1. [ ] If required, the desciption of your change is added to the [QA changelog](https://www.notion.so/octantapp/Changelog-for-the-QA-d96fa3b411cf488bb1d8d9a598d88281) 
2. [ ] Acceptance criteria are met.
3. [ ] PR is manually tested before the merge by developer(s).
    - [ ] Happy path is manually checked.
4. [ ] PR is manually tested by QA when their assistance is required (1).
    - [ ] Octant Areas & Test Cases are checked for impact and updated if required (2).
5. [ ] Unit tests are added unless there is a reason to omit them.
6. [ ] Automated tests are added when required.
7. [ ] The code is merged.
8. [ ] Tech documentation is added / updated, reviewed and approved (including mandatory approval by a code owner, should such exist for changed files).
    - [ ] BE: Swagger documentation is updated.
9. [ ] When required by QA:
    - [ ] Deployed to the relevant environment.
    - [ ] Passed system tests.

---

(1) Developer(s) in coordination with QA decide whether it's required. For small tickets introducing small changes QA assistance is most probably not required.

(2) [Octant Areas & Test Cases](https://docs.google.com/spreadsheets/d/1cRe6dxuKJV3a4ZskAwWEPvrFkQm6rEfyUCYwLTYw_Cc).

2024-12-20 13:46 UTC, aziolek requested changes
It needs to wait for FE part [here](https://linear.app/golemfoundation/issue/OCT-2264/ui-support-for-the-glm-giveaways-receivers).

2025-01-07 09:13 UTC, jmikolajczyk commented
/deploy

2025-02-07 11:41 UTC, aziolek approved these changes

2025-02-07 11:41 UTC, aziolek commented
I approve FE part (what @jmikolajczyk did) without what I did in https://github.com/golemfoundation/octant/pull/600/commits/09105efe7ed4d69fc0fd9086c1059fb257d7498c.

@jmikolajczyk: please check and let me know if it requires any adjustments.

2025-02-07 11:47 UTC, aziolek approved these changes

2025-02-07 11:53 UTC, jmikolajczyk commented
> I approve FE part (what @jmikolajczyk did) without what I did in [09105ef](https://github.com/golemfoundation/octant/commit/09105efe7ed4d69fc0fd9086c1059fb257d7498c) & [5907b8e](https://github.com/golemfoundation/octant/commit/5907b8e49487ae1a41e669edf71e89eb12eab958).
> 
> @jmikolajczyk: please check and let me know if it requires any adjustments.

@aziolek LGTM 👍

2025-02-07 12:25 UTC, aziolek commented
I changed the title of this PR to reflect regrouping of tickets in Linear.

2025-02-13 16:48 UTC, MateuszStoleckiGLM approved these changes
Approved for release and deployment

2025-02-13 17:01 UTC, merged