Migrate `/rewards` routes
golemfoundation/octant pull request #604
Opened 2024-12-23 09:32 UTC by adam-gf

## Description

   - `GET /rewards/budget/{address}/epoch/{epoch}`
   - `GET /rewards/budget/{address}/upcoming`
   - `GET /rewards/budgets/epoch/{epoch}`
   - `POST /rewards/estimated_budget/by_days`
   - `POST /rewards/estimated_budget`
   - `GET /rewards/leverage/{epoch}`
   - `GET /rewards/merkle_tree/{epoch}`
   - `GET /rewards/projects/epoch/{epoch}`
   - `GET /rewards/projects/estimated`
   - `GET /rewards/threshold/{epoch}`
   - `GET /rewards/unused/{epoch}`

2025-01-17 09:24 UTC, kgarbacinski commented on backend/app/context/epoch/block_range.py
> +    # start_block = get_block_num_from_ts(start_sec) if start_sec <= now_sec else None
it should be uncommented, right?

2025-01-17 09:24 UTC, kgarbacinski commented on backend/app/settings.py
> +        f"postgresql://postgres:mysecretpassword@localhost:5433/postgres"
let's remember to restore it as well

2025-01-17 09:26 UTC, kgarbacinski commented on backend/v2/core/contracts.py
> +        self.address = address
why is it needed here in the base class? is it used by all of children?

2025-01-17 09:27 UTC, kgarbacinski commented on backend/v2/core/dependencies.py
> +    def is_mainnet(self) -> bool:
i introduced `compare_blockchain_types` in my previous PR that is placed in the core; it should be unified to either my own way or yours for handling this

2025-01-17 09:36 UTC, kgarbacinski commented on backend/v2/deposits/repositories.py
> +        return user_events
for me this is more a part of service, isn't it? maybe let's try to keep it consistent and keep repository as a database layer only with the minimum of business logic?

2025-01-17 09:44 UTC, kgarbacinski commented on backend/v2/epochs/subgraphs.py
> +        return TypeAdapter(EpochSubgraphItem).validate_python(data[0])
maybe let's create an alias for that?

2025-01-17 09:44 UTC, kgarbacinski commented on backend/v2/epochs/subgraphs.py
> +        return TypeAdapter(EpochSubgraphItem).validate_python(data[0])
similar to `transform_to_checksum_address`

2025-01-17 09:50 UTC, kgarbacinski commented on backend/v2/project_rewards/capped_quadriatic.py
>  class CappedQuadriaticFunding(NamedTuple):
typo: Quadriatic --> Quadratic

2025-01-17 09:52 UTC, kgarbacinski commented on backend/v2/project_rewards/capped_quadriatic.py
>      amounts_total: Decimal  # Sum of all allocation amounts for all projects
```suggestion
    allocations_total_for_all_projects: Decimal  # Sum of all allocation amounts for all projects
```

2025-01-17 09:54 UTC, kgarbacinski commented on backend/v2/project_rewards/schemas.py
> +        return self.days * 86400  # 24hours * 60minutes * 60seconds
```suggestion
       return self.days * 24 * 60 * 60
```

2025-01-17 09:57 UTC, kgarbacinski commented on backend/v2/project_rewards/services.py
> +    return OctantRewardsDTO(
fancy but is it worth to turn off the formatter to have these values only justified in the code? 🚀

2025-01-17 10:02 UTC, kgarbacinski commented on backend/v2/project_rewards/user_events.py
this is a part of service, right? we do we keep it in the separate file `user_events`? if `services.py` is growing exponentially, let's maybe try to create a package `services` and create separate domain-related files out there? you can take a look at the `projects` package

2025-01-17 10:07 UTC, kgarbacinski commented on backend/v2/sablier/subgraphs.py
we'll also need to merge https://github.com/golemfoundation/octant/pull/600 to this one (there are some changes for getting streams for the giveaway winners)

2025-01-17 10:13 UTC, kgarbacinski commented on backend/v2/sablier/subgraphs.py
> +        if not os.path.exists("sablier_streams.json"):
it's very risky to cache it this way; we use sablier for computing `effective_deposit` just before every AW; if user does any single operation (like unlocking) just before the AW, we're in the deep ass because the result are not up-to-date with the real state, right?

2025-01-17 10:14 UTC, kgarbacinski requested changes
a few minor issues but also blockers to address

2025-01-28 00:03 UTC, adam-gf commented on backend/v2/core/contracts.py
> +        self.address = address
We use address for 
```

async def get_glm_balance_of_deposits(
    glm_contracts: GetGLMContracts,
    deposits_contracts: GetDepositsContracts,
) -> int:
    return await glm_contracts.balance_of(deposits_contracts.address)

```

2025-01-28 00:04 UTC, adam-gf commented on backend/v2/core/dependencies.py
> +    def is_mainnet(self) -> bool:
Changed to your approach with field with default lambda calling compare_blockchain_types

2025-01-28 00:05 UTC, adam-gf commented on backend/v2/epochs/subgraphs.py
> +        return TypeAdapter(EpochSubgraphItem).validate_python(data[0])
I'll do that once we will use it in more places than once here :)

2025-01-28 00:13 UTC, adam-gf commented on backend/v2/project_rewards/user_events.py
moved what's used to services

2025-01-28 00:15 UTC, adam-gf commented on backend/v2/sablier/subgraphs.py
> +        if not os.path.exists("sablier_streams.json"):
100% - it was just for local development

2025-01-28 10:55 UTC, kgarbacinski commented on backend/v2/project_rewards/capped_quadratic.py
> +    allocations_total_for_all_projects: Decimal  # Sum of all allocation amounts for all projects
are the comments useful now after we changed the variable name and it's sef-describing?

2025-01-29 10:39 UTC, kgarbacinski commented on backend/v2/sablier/subgraphs.py
> +            # logger.debug(f"[Sablier Subgraph] Querying streams with skip: {skip}")
to remove?

2025-01-29 10:40 UTC, kgarbacinski commented on backend/v2/sablier/subgraphs.py
> +            # app.logger.debug(f"[Sablier Subgraph] Received {len(streams)} streams.")
to remove?

2025-01-29 10:40 UTC, kgarbacinski commented on backend/v2/sablier/subgraphs.py
> +            # logger.debug(f"[Sablier Subgraph] Querying streams with skip: {skip}")
or uncomment

2025-01-29 10:40 UTC, kgarbacinski commented on backend/v2/sablier/subgraphs.py
> +            # app.logger.debug(f"[Sablier Subgraph] Received {len(streams)} streams.")
or uncomment

2025-01-29 10:40 UTC, kgarbacinski commented on backend/v2/sablier/subgraphs.py
> +        if not os.path.exists("sablier_streams.json"):
so to remove?

2025-01-29 11:52 UTC, kgarbacinski approved these changes

2025-01-30 08:36 UTC, merged